import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../../globals.css";
import { cn } from "@/lib/utils";
import { DatabaseProvider } from "@/context/database-context";

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DatabaseLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en" suppressHydrationWarning>
      <div
        className={cn(
          "min-h-screen font-sans antialiased",
          fontSans
        )}
      >
        <DatabaseProvider>{children}</DatabaseProvider>
      </div>
    </div>
  );
}
